#!/usr/bin/env bash

# script-name.sh
# script info
# Author: user@email.com
# Version: x.x
# Updated: date modified

# Return non-zero if any command in a pipeline fails
set -o pipefail

# use unified commands
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMMON_LIB="$SCRIPT_DIR/../common/common.sh"

#check if lib is missing
if [[ ! -f "$COMMON_LIB" ]]; then
    echo "ERROR: Missing common library: $COMMON_LIB" >&2
    exit 1
fi

# shellcheck disable=SC1090
source "$COMMON_LIB"

USE_COLOR=1
if [[ "${1:-}" == "--no-color" ]]; then
    USE_COLOR=0
fi

init_colors

# functions

# build main
main() {
    title "title"
    echo "a"
}

# call main
main "$@"